services:
  - type: web
    name: tradingview-mexc-webhook
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_SECRET
        sync: false
      - key: MEXC_API_KEY
        sync: false
      - key: MEXC_API_SECRET
        sync: false 